#
# Copyright (c) 2025 Rojar Smith
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

services:
  # ---------------------
  # MySQL service
  # ---------------------
  mysql:
    image: "mysql:8.0"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_USER=root is created by default in the container for mysql 8.0+
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /root/service/hawkbit/db/mysql_data:/var/lib/mysql
      - /root/service/hawkbit/config/mysql.cnf:/etc/mysql/mysql.cnf
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10
    labels:
      NAME: "mysql"

